import { 
  Shield, 
  Key, 
  Calendar, 
  Utensils, 
  Car, 
  Smartphone, 
  Brush, 
  Wrench,
} from 'lucide-react';
import { ServiceCategory, ServiceType, Requisition, ActivityLog, YearlyStat } from './types';

export const SERVICES: ServiceCategory[] = [
  {
    id: ServiceType.SAFETY,
    title: 'Safety & Security',
    description: 'Request security guards, access control, or report safety incidents.',
    icon: Shield,
  },
  {
    id: ServiceType.KEY_SERVICES,
    title: 'Key Services',
    description: 'Courier dispatch, document handling, and secure logistics.',
    icon: Key,
  },
  {
    id: ServiceType.EVENT_MANAGEMENT,
    title: 'Event Management',
    description: 'Book venues, organize corporate events, and catering setups.',
    icon: Calendar,
  },
  {
    id: ServiceType.CANTEEN,
    title: 'Staff Canteen',
    description: 'Meal vouchers, new employee registration, and guest catering.',
    icon: Utensils,
  },
  {
    id: ServiceType.TRANSPORT,
    title: 'Transport',
    description: 'Schedule pick-up/drop-off services or ad-hoc vehicle requests.',
    icon: Car,
  },
  {
    id: ServiceType.COMMUNICATIONS,
    title: 'Communications',
    description: 'SIM cards, data bundles, and mobile device provisioning.',
    icon: Smartphone,
  },
  {
    id: ServiceType.HOUSEKEEPING,
    title: 'Housekeeping',
    description: 'Cleaning services, office supplies, and pantry support.',
    icon: Brush,
  },
  {
    id: ServiceType.MAINTENANCE,
    title: 'Maintenance',
    description: 'Repairs for civil works, plumbing, washrooms, or office fixtures.',
    icon: Wrench,
  },
];

export const CURRENT_USER = {
  name: "Alex Sterling",
  id: "EMP-0042",
  department: "Product Engineering",
  avatarUrl: "https://picsum.photos/200",
};

export const ADMIN_USER = {
  name: "System Administrator",
  id: "ADM-31303",
  department: "IT Operations",
  avatarUrl: "https://ui-avatars.com/api/?name=Admin+User&background=6366f1&color=fff",
};

export const MOCK_REQUISITIONS: Requisition[] = [
  {
    id: 'REQ-1095',
    serviceId: ServiceType.SAFETY,
    requesterName: 'Alex Sterling',
    requesterId: 'EMP-0042',
    department: 'Product Engineering',
    date: '2023-10-25',
    status: 'Pending',
    summary: 'Temporary access card for visiting consultant',
  },
  {
    id: 'REQ-1092',
    serviceId: ServiceType.TRANSPORT,
    requesterName: 'Sarah Jenkins',
    requesterId: 'EMP-0092',
    department: 'Marketing',
    date: '2023-10-24',
    status: 'Pending',
    summary: 'Drop-off to Airport Terminal 3 at 18:00',
  },
  {
    id: 'REQ-1091',
    serviceId: ServiceType.MAINTENANCE,
    requesterName: 'David Chen',
    requesterId: 'EMP-0105',
    department: 'Finance',
    date: '2023-10-24',
    status: 'Pending',
    summary: 'Air conditioning malfunction in Room 402',
  },
  {
    id: 'REQ-1089',
    serviceId: ServiceType.CANTEEN,
    requesterName: 'Michael Rossi',
    requesterId: 'EMP-0033',
    department: 'HR',
    date: '2023-10-23',
    status: 'Approved',
    summary: 'Guest Lunch for 5 visitors (Vegetarian)',
  },
  {
    id: 'REQ-1088',
    serviceId: ServiceType.KEY_SERVICES,
    requesterName: 'Jessica Wu',
    requesterId: 'EMP-0088',
    department: 'Legal',
    date: '2023-10-23',
    status: 'Rejected',
    summary: 'Courier dispatch to Singapore HQ',
  },
  {
    id: 'REQ-1085',
    serviceId: ServiceType.COMMUNICATIONS,
    requesterName: 'Alex Sterling',
    requesterId: 'EMP-0042',
    department: 'Product Engineering',
    date: '2023-10-22',
    status: 'Approved',
    summary: 'Data Bundle Top-up (50GB) for remote work',
  },
  {
    id: 'REQ-1082',
    serviceId: ServiceType.HOUSEKEEPING,
    requesterName: 'Alex Sterling',
    requesterId: 'EMP-0042',
    department: 'Product Engineering',
    date: '2023-10-20',
    status: 'Approved',
    summary: 'Deep cleaning for Lab 3 after spill',
  },
];

export const MOCK_ACTIVITY_LOG: ActivityLog[] = [
  {
    id: 'LOG-5021',
    action: 'Approved request REQ-1089',
    user: 'Admin (31303)',
    timestamp: '2 hours ago',
    type: 'success',
  },
  {
    id: 'LOG-5020',
    action: 'Rejected request REQ-1088 due to incomplete address',
    user: 'Admin (31303)',
    timestamp: '5 hours ago',
    type: 'error',
  },
  {
    id: 'LOG-5019',
    action: 'System Maintenance scheduled for 25th Oct',
    user: 'System',
    timestamp: '1 day ago',
    type: 'info',
  },
  {
    id: 'LOG-5018',
    action: 'New policy updated for Transport Services',
    user: 'HR Manager',
    timestamp: '2 days ago',
    type: 'info',
  },
];

export const MOCK_YEARLY_STATS: YearlyStat[] = [
  {
    serviceId: ServiceType.SAFETY,
    totalRequests: 145,
    approved: 128,
    rejected: 12,
    pending: 5,
    avgProcessingTime: '2h 15m',
    budgetUtilized: 75,
  },
  {
    serviceId: ServiceType.KEY_SERVICES,
    totalRequests: 89,
    approved: 80,
    rejected: 9,
    pending: 0,
    avgProcessingTime: '4h 00m',
    budgetUtilized: 45,
  },
  {
    serviceId: ServiceType.EVENT_MANAGEMENT,
    totalRequests: 32,
    approved: 28,
    rejected: 1,
    pending: 3,
    avgProcessingTime: '2d 4h',
    budgetUtilized: 92,
  },
  {
    serviceId: ServiceType.CANTEEN,
    totalRequests: 215,
    approved: 210,
    rejected: 5,
    pending: 0,
    avgProcessingTime: '15m',
    budgetUtilized: 60,
  },
  {
    serviceId: ServiceType.TRANSPORT,
    totalRequests: 340,
    approved: 310,
    rejected: 20,
    pending: 10,
    avgProcessingTime: '1h 30m',
    budgetUtilized: 85,
  },
  {
    serviceId: ServiceType.COMMUNICATIONS,
    totalRequests: 67,
    approved: 60,
    rejected: 5,
    pending: 2,
    avgProcessingTime: '1d 2h',
    budgetUtilized: 40,
  },
  {
    serviceId: ServiceType.HOUSEKEEPING,
    totalRequests: 412,
    approved: 405,
    rejected: 5,
    pending: 2,
    avgProcessingTime: '45m',
    budgetUtilized: 78,
  },
  {
    serviceId: ServiceType.MAINTENANCE,
    totalRequests: 156,
    approved: 140,
    rejected: 6,
    pending: 10,
    avgProcessingTime: '3h 20m',
    budgetUtilized: 65,
  },
];